
package view;
import com.mycompany.clinica.Conexion;

public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        Usser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        password = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        entrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setText("CLINICA ");

        Usser.setText("Usuario");

        jScrollPane1.setViewportView(jEditorPane1);

        password.setText("Contraseña");

        jScrollPane2.setViewportView(jEditorPane2);

        entrar.setText("Entrar");
        entrar.addActionListener(this::entrarActionPerformed);

        jButton1.setText("Nuevo usuario");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entrar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password)
                                    .addComponent(Usser))
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(titulo)))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(3, 3, 3)
                .addComponent(titulo)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usser))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(entrar)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Crear una instancia de la ventana de registro
    NuevoUsuario ventanaRegistro = new NuevoUsuario(); 
    
    // 2. Hacer visible la nueva ventana
    ventanaRegistro.setVisible(true);
    
    // 3. Cerrar (ocultar) la ventana de Login actual
    this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed

            // 1. Obtener el texto ingresado en los campos
    String usuario = jEditorPane1.getText().trim();
    String contrasena = jEditorPane2.getText().trim();
    
    // Validar que el usuario no deje los campos en blanco
    if (usuario.isEmpty() || contrasena.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. Consulta SQL (Ajusta los nombres si tu tabla o campos son diferentes)
    String sql = "SELECT * FROM usuario WHERE username = ? AND password_hash = ? AND estado = 1";
    
    // 3. Conectar a MySQL usando tu clase Conexion
    try (java.sql.Connection con = Conexion.conectar(); 
         java.sql.PreparedStatement pst = con.prepareStatement(sql)) {
        
        if (con == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos. Verifique XAMPP.", "Error de Conexión", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Pasar los datos de forma segura
        pst.setString(1, usuario);
        pst.setString(2, contrasena);
        
        try (java.sql.ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido a la Clínica!", "Login Exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); // Cierra la ventana actual de Login
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Acceso Denegado", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        
    } catch (java.sql.SQLException e) {
        logger.log(java.util.logging.Level.SEVERE, "Error en el proceso de login", e);
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error en el sistema: " + e.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_entrarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Usser;
    private javax.swing.JButton entrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel password;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
